# Source directory/path.
SRCPATH:
# Where your apache source files are located.
APACHE_SRCPATH: /var/www
# NGINX source files.
NGINX_SRCPATH: /var/www
# Your apache config files.
APACHE_BASEPATH: /etc/apache2
# Your NGINX config files.
NGINX_BASEPATH: /usr/local/etc/nginx
# Your default apache PORT
APACHE_PORT: 8080
